services:
  xv6-labs-2022:
    build: .
    container_name: xv6-labs-2022
    tty: true
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ../:/root/xv6-labs-2022 # 本地目录挂载到容器
      - /Users/erix/.ssh:/root/.ssh:ro # 挂载 SSH 密钥
